spring.application.name=alert_case_service_detection
server.port=9008

# ===============================
# Datasource
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/fraud_detection?autoReconnect=true
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect

# ===============================
# Kafka
# ===============================
spring.kafka.bootstrap-servers=localhost:9092

# Kafka Consumer Configuration
spring.kafka.consumer.group-id=alert-case-service-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

# Kafka Producer Configuration
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

# ===============================
# Logging
# ===============================
logging.level.root=INFO
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.kafka=DEBUG
logging.level.com.example.audit_compliance_service_fraud_detectio=DEBUG
logging.level.com.api.alert_case_service_detection=DEBUG

# Include Correlation ID in logs
logging.pattern.level=%5p [X-Correlation-Id=%X{X-Correlation-Id}]

# ===============================
# Management Endpoints
# ===============================
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=when-authorized
