# Development environment configuration

# ===============================
# Development Kafka Configuration
# ===============================
spring.kafka.bootstrap-servers=localhost:9092

# ===============================
# Development PostgreSQL Configuration
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/fraud_detection?autoReconnect=true
spring.datasource.username=postgres
spring.datasource.password=root

# ===============================
# Development Redis Configuration
# ===============================
spring.data.redis.host=localhost
spring.data.redis.port=6379

# ===============================
# Development Logging
# ===============================
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.reactor.netty.http.client=DEBUG
logging.level.org.springframework.kafka=DEBUG
