spring.application.name=audit_compliance_service_fraud
server.port=9007

# ===============================
# Database
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/fraud_detection?autoReconnect=true
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect

# ===============================
# Kafka
# ===============================
spring.kafka.bootstrap-servers=localhost:9092

# Kafka Consumer Configuration
spring.kafka.consumer.group-id=fraud-action-service-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer


# ===============================
# Logging
# ===============================
logging.level.root=INFO
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.kafka=DEBUG
logging.level.com.example.audit_compliance_service_fraud=DEBUG
logging.level.com.api.audit_compliance_service_fraud=DEBUG

# Include Correlation ID in logs
logging.pattern.level=%5p [X-Correlation-Id=%X{X-Correlation-Id}]