spring.application.name=risk_score_service_fruad
server.port=9004

# ===============================
# Kafka
# ===============================
spring.kafka.bootstrap-servers=localhost:9092

# ===============================
# Logging
# ===============================
logging.level.root=INFO
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.kafka=DEBUG
logging.level.com.api.risk_score_service_fruad=DEBUG

# Include Correlation ID in logs
logging.pattern.level=%5p [X-Correlation-Id=%X{X-Correlation-Id}]
