spring.application.name=transaction_service_fraud
server.port=9002

# ===============================
# JWT Validation (Resource Server)
# ===============================
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:9001/oauth2/jwks

# ===============================
# Database
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/fraud_detection?autoReconnect=true
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect

# ===============================
# Kafka
# ===============================
spring.kafka.bootstrap-servers=localhost:9092

# ===============================
# Logging Levels
# ===============================
logging.level.root=INFO
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=INFO
logging.level.org.springframework.kafka=DEBUG
logging.level.com.example.transaction_service_fraud_detection=DEBUG

# Include MDC values in logs
logging.pattern.level=%5p [X-Correlation-Id=%X{X-Correlation-Id}]